Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=32000, mem_mib=30518, disk_mb=1000, disk_mib=954, gpu=1
Select jobs to execute...

[Thu Dec 14 09:38:22 2023]
rule test_prior:
    input: train_prior_outputs/protT5_128_sigmoid_100.out
    output: results/test_prior_rows/protT5_128_sigmoid_100
    jobid: 0
    reason: Missing output files: results/test_prior_rows/protT5_128_sigmoid_100
    wildcards: lm=protT5, dimension=128, activation=sigmoid, num_components=100
    threads: 4
    resources: mem_mb=32000, mem_mib=30518, disk_mb=1000, disk_mib=954, tmpdir=/tmp, partition=vision, gpu=1, runtime=60


        cd .. && python3 TestPrior.py --lm protT5 --reduced_dim 128             --activation sigmoid --components 100 --unscaled > train_scoring_models/results/test_prior_rows/protT5_128_sigmoid_100
        
Traceback (most recent call last):
  File "/home/beckerf/tmp_work/learnMSA/learnMSA/protein_language_models/TestPrior.py", line 19, in <module>
    from learnMSA.protein_language_models.MultivariateNormalPrior import make_pdf_model, aggregate
ModuleNotFoundError: No module named 'learnMSA.protein_language_models.MultivariateNormalPrior'
[Thu Dec 14 09:38:27 2023]
Error in rule test_prior:
    jobid: 0
    input: train_prior_outputs/protT5_128_sigmoid_100.out
    output: results/test_prior_rows/protT5_128_sigmoid_100

RuleException:
CalledProcessError in file /home/beckerf/tmp_work/learnMSA/learnMSA/protein_language_models/train_scoring_models/Snakefile, line 90:
Command 'set -euo pipefail;  
        cd .. && python3 TestPrior.py --lm protT5 --reduced_dim 128             --activation sigmoid --components 100 --unscaled > train_scoring_models/results/test_prior_rows/protT5_128_sigmoid_100' returned non-zero exit status 1.
  File "/home/beckerf/tmp_work/learnMSA/learnMSA/protein_language_models/train_scoring_models/Snakefile", line 90, in __rule_test_prior
  File "/home/beckerf/mambaforge/envs/snakeMSA/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job test_prior since they might be corrupted:
results/test_prior_rows/protT5_128_sigmoid_100
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
